# basic 2 .1 데이터 다듬기 - 배열, 데이터 프레임 만들기

### 1.1 Numpy : 배열

In [55]:
import numpy as np

In [56]:
# *2 
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
a = a*2
print(a)    

[1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18]


In [57]:
# 짝수만 표시
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[a%2 == 0])

[2 4 6 8]


In [58]:
# 홀수만 표시
a = np.array([1,2,3,4,5,6,7,8,9])
print(a[a%2 != 0])

[1 3 5 7 9]


In [63]:
a = [1,2,3,4]

# 배열로 만들기
b = np.array(a)
print(b)
# 차원 확인
print(b.ndim)
# 형태 확인
print(b.shape)
# 자료형 확인
print(b.dtype)

[1 2 3 4]
1
(4,)
int32


In [65]:
# 2차원 배열 만들기
a = [1,2,3,4],[5,6,7,8.0]

b = np.array(a)
print(b)
# 차원 확인
print(b.ndim)
# 형태 확인
print(b.shape)
# 자료형 확인
print(b.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
2
(2, 4)
float64


### 1.2 rashape : 배열의 형태 바꾸기

In [78]:
# 2,3 - > 3,2
a = np.array([[1,2,3],
             [4,5,6]])

print(a)
print('-'*10)
b = a.reshape(3,2)
print(b)

[[1 2 3]
 [4 5 6]]
----------
[[1 2]
 [3 4]
 [5 6]]


### 1.3 배열 인덱싱과 슬라이싱

In [89]:
# 인덱싱
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

# 첫번째 행, 두번째 열 조회
print(a[0,1])
print('-'*20)

# 첫번째, 두번째, 세번째 행 조회
print(a[[0,1,2],:])

2
--------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [93]:
# 슬라이싱
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])

# 첫번째 ~ 두번째 행 조회
print(a[0:2,:])
print('-'*20)

# 첫번째 ~ 세번째 행, 두번째 ~ 세번째 열 조회
print(a[:3,1:3])

[[1 2 3]
 [4 5 6]]
--------------------
[[2 3]
 [5 6]
 [8 9]]


### 1.4 조건 조회

In [97]:
# 조건 조회

score = np.array([[78,68,46,78],
                   [90,96,99,100]])

# 90 이상인 것만 조회
print(score[score >= 90])
print('-'*20)

# 50 이상, 90 미만
print(score[(score >=50) & (score < 90)])

[ 90  96  99 100]
--------------------
[78 68 78]


### 2. pandas이용한 데이터 프레임

In [108]:
import pandas as pd

# 데이터 프레임 만들기 

# 1. 1차원 리스트로 만들기
tmp = [1,2,3]

df = pd.DataFrame(tmp)
print(df)
print('-'*50)

# 2. 2차원 리스트로 만들기
tmp = [[1,2,3],
      [4,5,6]]

df = pd.DataFrame(tmp)
print(df)
print('-'*50)

# 3. 열 이름, 인덱스 이름 지정
tmp = [[1,2,3],
      [4,5,6],
      [7,8,9]]
dates = ['22.02.13','22.02.14','22.02.15']
names = ['취','뽀','!']
df = pd.DataFrame(tmp, index = dates,columns=names)

print(df)

   0
0  1
1  2
2  3
--------------------------------------------------
   0  1  2
0  1  2  3
1  4  5  6
--------------------------------------------------
          취  뽀  !
22.02.13  1  2  3
22.02.14  4  5  6
22.02.15  7  8  9
